### ISSUE TITLE
After update my Macbook pro to macOS Big Sur K40 Whisperer don't start anymore ? some one can fix it maybe?

### ISSUE THREAD

**Issue by BC-57** [rsre/K40-Whisperer-macOS#10]

**Comment by rsre** [comment]
Hi BC-57,

Could you be more specific about how are you using K40 Whisperer?

I haven't upgraded my machine to Big Sur, but I do have a Virtual Machine running the latest version. Right now a build can't be completed on Big Sur (due to problems with Homebrew and some Python stuff), but the old app bundle should work without problems. You might have to allow the app to run in System Preferences -> Security & Privacy in the General tab.

<img width="838" alt="Screenshot 2020-12-24 at 16 07 50" src="https://user-images.githubusercontent.com/12608029/103095805-3354b380-4602-11eb-9f14-0e03a73b819f.png">

**Comment by BC-57** [comment]
it says me K 40 Whisperer terminated unexpectedly . I just installed everything new but it won't start .
looks like this .

I use the k40 with my MacBook Pro via usb. but before the update from Catalina to Big Sur everything worked fine .

<img width="460" alt="Bildschirmfoto 2020-12-24 um 16 22 45" src="https://user-images.githubusercontent.com/76560375/103096465-48cadd00-4604-11eb-8a5e-b950ca702bf8.png">

**Comment by rsre** [comment]
That happens as soon as you open the program or after trying to complete some action?

I'm trying to figure out what might be causing it.

**Comment by BC-57** [comment]
That happens as soon as i open the program

**Comment by BC-57** [comment]
if I want to start the program with terminal this happened 
maybe you need this information?

<img width="1333" alt="Bildschirmfoto 2020-12-24 um 16 40 37" src="https://user-images.githubusercontent.com/76560375/103097195-d27baa00-4606-11eb-862d-8ec0c19cbe63.png">

**Comment by rsre** [comment]
Alright, after updating to macOS 11.1 I get the crash too. I'll investigate further during the holidays to see if I can find the problem and a fix for it.

Happy holidays!


EDIT: Apparently it's a known problem with tkinter https://bugs.python.org/issue42480

**Comment by BC-57** [comment]
Happy Hollidays To And thank you .

**Comment by BC-57** [comment]
> Alright, after updating to macOS 11.1 I get the crash too. I'll investigate further during the holidays to see if I can find the problem and a fix for it.
> 
> 
> 
> Happy holidays!
> 
> 
> 
> 
> 
> EDIT: Apparently it's a known problem with tkinter https://bugs.python.org/issue42480

Okay But what i have To do now i Cant programming. I can only Download a final Version of One is ready .

**Comment by rsre** [comment]
Hi BC-57,

I have created a new release that uses a new tkinter version and should work on macOS 11.1 (at least it does work on my Virtual Machine).

You can download it here https://github.com/rsre/K40-Whisperer-macOS/releases/tag/v0.54.B

If you test it let me know if everything works fine for you.

Enjoy :)

**Comment by BC-57** [comment]
Really Perfect Thank You very much you made my Hollidays Great again.!! and I can work with my k40 again.. thx for the fastest support Ive ever get in my life .
Thank You .

<img width="1231" alt="Bildschirmfoto 2020-12-25 um 01 12 36" src="https://user-images.githubusercontent.com/76560375/103111554-8eac9300-464e-11eb-8898-1d40c21bdd70.png">

**Comment by rsre** [comment]
You are welcome. Enjoy your laser during the holidays!
