### ISSUE TITLE
PyInstaller fails on Code Signing in macOS 10.12

### ISSUE THREAD

**Issue by nxreigle** [rsre/K40-Whisperer-macOS#19]
Quick fix, for anyone encountering "invalid or unsupported for signature" at the packaging stage. 

Apparently there is an issue related to the way pyinstaller handles ad-hoc signing after version 4.3 that conflicts with older macOS. 

The way I fixed it, was to change "pyinstaller" in  requirements.txt to "pyinstaller==4.3". 

Then everything worked like a charm.

**Comment by rsre** [comment]
Thanks for the heads-up! Do you want to make a Pull Request to leave that annotated somewhere on the README?
