### ISSUE TITLE
No connection to laser

### ISSUE THREAD

**Issue by knutaugust** [rsre/K40-Whisperer-macOS#21]
Hi,
The application works fine, but when i try to initialize my k40, it doesn’t find it. It says: USB Error: Laser USB Device not found. (libUSB driver may not be installed). But libUSB is installed.  Any suggestions what can be wrong?

**Comment by rsre** [comment]
Just to rule things out: what version of macOS are you using?

**Comment by knutaugust** [comment]
I’m using Big Sur 11.6 on that Mac.

**Comment by knutaugust** [comment]
It’s working for me now. I replaced the USB cable and it connected right away.

**Comment by rsre** [comment]
Awesome. I'll close this issue then. Have fun.
