### ISSUE TITLE
Main document display video disappears

### ISSUE THREAD

**Issue by EverlastEngineering** [rsre/K40-Whisperer-macOS#24]
The main document area showing the display disappears after most functions that update that area. It occasionally blinks and reappears. Resizing or moving the window always fixes it.

OS Montery 12.2.1 on a MacBook Pro
Mono JIT compiler version 6.12.0.113
Inkscape 1.1.2 (installed from DMG)

To reproduce:
Open example file on DMG. Click the right arrow to move the image right. It appears then disappears, leaving a blank area. Each click moving the image causes the image to appear briefly then disappear. 

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/2895375/165004149-173b9ff3-cf8a-4740-ad07-e61c5f7086a3.png">

Moving or resizing the window fixes the display:
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/2895375/165004136-22d8fa44-03f1-4a6f-8396-a2a0b2773210.png">

Happy to provide any further information.

**Comment by EverlastEngineering** [comment]
(I installed Inkscape via cask to test, no change.)

**Comment by rsre** [comment]
Thanks for the report.

I'll give it a look as soon as I can. Something similar happened in the past so I'll need to dig the details to check how it got addressed last time.

Apart from the rendering, is the build usable? Are you able to communicate with the laser and cut stuff?

**Comment by rsre** [comment]
I've been testing various test builds to try to pin-point the cause of the problem. I haven't been able to find it yet.

I'll keep testing different python versions and partially apply Scorch patches and see if I manage to find what's causing the failed reloads.

**Comment by EverlastEngineering** [comment]
I’ve got a MacBook Air with big sur, fresh brew and Inkscape installed via
brew with the same issue. Want me to get version info? Should be all
latest. I can swap in python versions or Inkscape versions too.

**Comment by EverlastEngineering** [comment]
I'll be able to test the functionality of moving the laser around today as
well from both laptops, the machine was disassembled prior to this.

**Comment by rsre** [comment]
Hello @EverlastEngineering! Can you test if the issue persists in the latest release ([v0.62.0](https://github.com/rsre/K40-Whisperer-macOS/releases/tag/v0.62.0))?

**Comment by EverlastEngineering** [comment]
Sure, I'll see if I can try this weekend!
