### ISSUE TITLE
App does not open on M1 MacBook Air

### ISSUE THREAD

**Issue by godomac** [rsre/K40-Whisperer-macOS#28]
I can't get the app to open. If I go into the package and start the app from the MacOS folder directly this message shows up in the terminal:

[27543] Error loading Python lib '/var/folders/wr/mvyy74l90_vd3z_vfh3s1jj40000gn/T/_MEIHB6rm9/Python': dlopen: dlopen(/var/folders/wr/mvyy74l90_vd3z_vfh3s1jj40000gn/T/_MEIHB6rm9/Python, 0x000A): Symbol not found: (_mkfifoat)
  Referenced from: '/private/var/folders/wr/mvyy74l90_vd3z_vfh3s1jj40000gn/T/_MEIHB6rm9/Python'
  Expected in: '/usr/lib/libSystem.B.dylib'

**Comment by rsre** [comment]
Hello @godomac! It seems to be [an issue regarding code signing](https://github.com/pyinstaller/pyinstaller/issues/5062). I don't know if I can reproduce it in my own machine.

I'm not sure I can sign applications because I don't have an Apple Developer account. I'll see what I can do.

**Comment by rsre** [comment]
Hey @godomac I was able to open the app on an M1 with Ventura 13.4 (22F66), have you tried again recently to check if the issue is still happening?

**Comment by godomac** [comment]
Now it's working on my system, too! Thanks for your response!

**Comment by rsre** [comment]
> Now it's working on my system, too! Thanks for your response!

Great to hear that 👍
