### ISSUE TITLE
GRBL support?

### ISSUE THREAD

**Issue by dhysuiej** [rsre/K40-Whisperer-macOS#30]
I have a cheap Chinese 3018 CNC that came with LaserGRBL, but that app is Windows only. Would K40-Whisperer-macOS work with GRBL1.1 Control Boards?

**Comment by rsre** [comment]
Hi @dhysuiej, this a repackaging of [K40 Whisperer](https://www.scorchworks.com/K40whisperer/k40whisperer.html) with some adjustments to work on MacOS. On their site you'll find [a list of compatible boards](https://www.scorchworks.com/K40whisperer/k40whisperer.html#boards), but short answer: no, this program is not compatible with LaserGRBL.
